### ISSUE TITLE
Error in importing pyvista and fixing it from the code of dem2vtk

### ISSUE THREAD

**Issue by waqashussain117** [gecos-lab/PZero#103]
Taking clues from dem2vtk to correct pyvista2vtk.py. Error: entity_dict Properly:

Traceback (most recent call last):
  File "C:\Users\Waqas Hussain\OneDrive - Universit� degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\project_window.py", line 153, in <lambda>
    self.actionImportPyvista.triggered.connect(lambda: pyvista2vtk(self=self))
                                                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Waqas Hussain\OneDrive - Universit� degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\imports\pyvista2vtk.py", line 83, in pyvista2vtk
    self.e_c.add_entity_from_dict(
    ^^^^^^^^
AttributeError: 'ProjectWindow' object has no attribute 'e_c' 
Adding comments from previous code

replacing e_c with ap proper call to add entity from dict from geological collection not from e_c.
Constructing entity_dict Properly:

Just like in dem2vtk.py, we create an entity_dict named curr_obj_attributes by deep copying self.geol_coll.entity_dict.
I populate curr_obj_attributes with all necessary keys, including:
uid: A unique identifier generated using str(uuid4()).
name: The base name of the input file.
topology: The type of the entity (e.g., "VertexSet", "PolyLine", etc.).
vtk_obj: The curr_obj we read using pv_read.
properties_names and properties_components: Empty lists, unless you have specific properties to add.
Assigning the Correct Class to curr_obj:

We need to set curr_obj.__class__ to the appropriate class from pzero.entities_factory based on the cell type.
We also set a topology variable to use in the entity_dict.
Adding the Entity to the Collection:

We call self.geol_coll.add_entity_from_dict(entity_dict=curr_obj_attributes) to add the entity to the geological collection
because the previous code didn't had proper call to the collection

**Comment by waqashussain117** [comment]
ITS fixed now I have made the changes, you can now import vtk or pyvista files into pzero. The code is mostly copied from dem2vtk thanks for the hinting comments.
