### ISSUE TITLE
Error in Pointscloud import fixing

### ISSUE THREAD

**Issue by waqashussain117** [gecos-lab/PZero#104]
: . Reading and importing file
2. Checking the data
3. Creating PointCloud
4. Adding PC to project
Traceback (most recent call last):
  File "C:\Users\Waqas Hussain\OneDrive - Universit� degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\project_window.py", line 2162, in import_PC
    pc2vtk(
  File "C:\Users\Waqas Hussain\OneDrive - Universit� degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\imports\pc2vtk.py", line 181, in pc2vtk
    curr_obj_attributes["uid"] = str(uuid4())
    ~~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: 'property' object does not support item assignment
before
curr_obj_attributes = deepcopy(DomCollection.entity_dict)

after

curr_obj_attributes = deepcopy(DomCollection().entity_dict)

The same problem also happened with other imports. accessing DOMCollection by using brackets. The same error happened also in dem2vtk pyvista2vtj and well2vtk

it is fixed now. However, I am not sure that the pointcloud being viewed in 3d viewer is accurate as it only shows a few points. needs to be discussed

**Comment by waqashussain117** [comment]
Fixed now, point cloud data such as text and csv can be imported. However, the viewing of the pointcloud data doesn't seems to be accurate in my view.
