### ISSUE TITLE
Needs to put openpyxl for wells in the environment. Module not found

### ISSUE THREAD

**Issue by waqashussain117** [gecos-lab/PZero#108]
Traceback (most recent call last):
  File "C:\Users\Waqas Hussain\OneDrive - Università degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\project_window.py", line 2265, in import_welldata
    well2vtk(self, path=path)
  File "C:\Users\Waqas Hussain\OneDrive - Università degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\imports\well2vtk.py", line 34, in well2vtk
    data = pd_read_excel(path, sheet_name=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\pzero6\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\pzero6\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\pzero6\Lib\site-packages\pandas\io\excel\_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\pzero6\Lib\site-packages\pandas\io\excel\_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\pzero6\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 556, in __init__
    import_optional_dependency("openpyxl")
  File "C:\ProgramData\anaconda3\envs\pzero6\Lib\site-packages\pandas\compat\_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

I forgot to add that we need to put openpyxl in the envionment in the environment.yml for installation as it is being missed by for some reason. After I installed the environment for PySide6, and try to import well into PZero I found this issue. I don't know why conda missed out on this. Need to look into this.

**Comment by andrea-bistacchi** [comment]
I'm not sure about this. I do not find where we use `openpyxl`, that is used to read Excel files. It was used in the past by some importer but apparently no more, since now we use `pandas`.

**Comment by waqashussain117** [comment]
Well I encountered it while importing wells, maybe its not here anymore. need to built a new environment and test it.

**Comment by andrea-bistacchi** [comment]
We do not import `openpyxl` in any module in **PZero**, so it really seems strange it was required.

Maybe it was required by some library we used in the past? Not clear since it is not listed in the [pzero environment file](https://github.com/gecos-lab/PZero/blob/class_refactoring_pyside6/envs/pzero-env.yml).

Anyway, please try reproducing the problem you had originally, bu with the brand new [pzero environment](https://github.com/gecos-lab/PZero/blob/class_refactoring_pyside6/envs/pzero-env.yml) freshly installed, ad we will see if it is fixed or not.

**Comment by gbene** [comment]
Hi! openpyxl is a package **necessary** for reading/writing excel files with pandas. It was used for the wells because we started developing wells using mainly excel files as input.

**Comment by andrea-bistacchi** [comment]
It is listed as a requirement for pandas [here](https://anaconda.org/anaconda/pandas/files), so it should be added automatically to the environment.

@waqashussain117 please test importing some well.

**Comment by andrea-bistacchi** [comment]
OK, I've added it to the environment.

It's pretty strange it was not included as a default dependency.

Closed with 42d109ad.
