### ISSUE TITLE
Resemple Distance tool is not working

### ISSUE THREAD

**Issue by r-monti14** [gecos-lab/PZero#118]
Traceback (most recent call last):
  File "D:\REPOS\PZero\pzero\windows_factory.py", line 3021, in <lambda>
    self.resampleDistanceButton.triggered.connect(lambda: resample_line_distance(self))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\REPOS\PZero\pzero\two_d_lines.py", line 924, in resample_line_distance
    shp_line_out = shp_linestring(points)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Riccardo\anaconda3\envs\pzero6\Lib\site-packages\shapely\geometry\linestring.py", line 66, in __new__
    coordinates = [_coords(o) for o in coordinates]
                   ^^^^^^^^^^
  File "C:\Users\Riccardo\anaconda3\envs\pzero6\Lib\site-packages\shapely\geometry\linestring.py", line 64, in _coords
    return [float(c) for c in o]
            ^^^^^^^^
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by r-monti14** [comment]
Solved with [3f6192d](https://github.com/gecos-lab/PZero/commit/3f6192dc3bc258d71766aacc8814ea8ebe6754dd)
