### ISSUE TITLE
Fail to load test models

### ISSUE THREAD

**Issue by saeidzk** [gecos-lab/PZero#121]
While loading both Simple-synthetic and Llyn-Padarn I got the error:

Traceback (most recent call last):
  File "pzero\project_window.py", line 1088, in open_project
  File "pandas\util\_decorators.py", line 311, in wrapper
  File "pandas\core\frame.py", line 6313, in sort_values
  File "pandas\core\generic.py", line 1840, in _get_label_or_level_values
KeyError: 'geological_time'

I tried both with the executable Windows version and the binaries version in the Anaconda environment.

**Comment by andrea-bistacchi** [comment]
Hi, on which branch you are testing? We are carrying out a large scale refactoring and many things are broken in the master branch. This is expected to be solved in a few days.
