### ISSUE TITLE
Pandas: .append() method does not seem to be supported for series in recent versions.

### ISSUE THREAD

**Issue by r-monti14** [gecos-lab/PZero#123]
In the function replace_vtk (in GFB_collection.py), the method .append() is not supported. 

_Traceback (most recent call last):
  File "D:\REPOS\PZero\pzero\project_window.py", line 205, in <lambda>
    self.actionProject2DEM.triggered.connect(lambda: project_2_dem(self))
                                                     ^^^^^^^^^^^^^^^^^^^
  File "D:\REPOS\PZero\pzero\helpers\helper_functions.py", line 292, in wrapper
    func(self, *args, **kwargs)
  File "D:\REPOS\PZero\pzero\three_d_surfaces.py", line 1622, in project_2_dem
    self.geol_coll.replace_vtk(uid=uid, vtk_object=obj_dict["vtk_obj"])
  File "D:\REPOS\PZero\pzero\collections\GFB_collection.py", line 207, in replace_vtk
    self.df.loc[self.df["uid"] == uid, "properties_names"].append(key)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Riccardo\anaconda3\envs\pzero6\Lib\site-packages\pandas\core\generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'append'. Did you mean: '_append'?_

It seems that to fix the problem, it's better replace:
_keys = vtk_object.point_data_keys
            self.df.loc[self.df["uid"] == uid, "properties_names"].values[0] = []
            self.df.loc[self.df["uid"] == uid, "properties_components"].values[0] = []_
With:
_index = self.df.index[self.df["uid"] == uid][0]
            self.df.at[index, "properties_names"] = []
            self.df.at[index, "properties_components"] = []_
            
I will test this part tomorrow

**Comment by r-monti14** [comment]
Fixed with 8c0eedf7f5afcc7c7df8e06de1631d5e15836b71
