### ISSUE TITLE
Fiona needs a downgrade in the requirements of ENV file of pzero5

### ISSUE THREAD

**Issue by waqashussain117** [gecos-lab/PZero#99]
Traceback (most recent call last):
  File "C:\Users\Waqas Hussain\OneDrive - Universitα degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\project_window.py", line 2186, in import_SHP
    shp2vtk(self=self, in_file_name=in_file_name, collection=coll)
  File "C:\Users\Waqas Hussain\OneDrive - Universitα degli Studi di Milano-Bicocca\Documents\GitHub\PZero\pzero\imports\shp2vtk.py", line 35, in shp2vtk
    gdf = gpd_read_file(in_file_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Waqas Hussain\anaconda3\envs\pzero\Lib\site-packages\geopandas\io\file.py", line 297, in _read_file
    return _read_file_fiona(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Waqas Hussain\anaconda3\envs\pzero\Lib\site-packages\geopandas\io\file.py", line 315, in _read_file_fiona
    if _is_zip(str(path_or_bytes)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Waqas Hussain\anaconda3\envs\pzero\Lib\site-packages\geopandas\io\file.py", line 173, in _is_zip
    parsed = fiona.path.ParsedPath.from_uri(path)
             ^^^^^^^^^^
AttributeError: module 'fiona' has no attribute 'path'. Did you mean: 'Path'?

Fiona has a recent update o 1.10.0 (as of 2024-09-04 01:14 UTC) and that may have broken some older versions of geopandas, which only depend on fiona being higher than some version, not lower than.

To ensure compatibility with Geopandas, downgrade Fiona to the latest version in the 1.9.4.

**Comment by andrea-bistacchi** [comment]
This will be fixed when we'll be able to upgrade to `pandas >=2` (but this requires refactoring where the `append` method is used on dataframes).

Before doing that, we can try:

1) forcing `geopandas  >= 0.14.4` in the "from history" environment and rebuilding the environment.

2) (if (1) does not work) adding `fiona = 1.9.6` in the "from history" environment and rebuilding the environment.

**Comment by waqashussain117** [comment]
After upgrading to geopandas = 0.14.4 the import of the shapefile works, So I think it we can just update geopandas instead. I tested this in class_refactoring_PySide6.

**Comment by waqashussain117** [comment]
After adding geopandas = 0.14.4 I encountered another problem that was with the value of Z which was expected by the shape file. I have resolved that in the recent commit of shp2vtk. I applied that also in PyQt5 version but forgot to mention it.

**Comment by andrea-bistacchi** [comment]
Closed with 5fe6c364.
